on:
    push:
        branches:
        - main

jobs:
    download_video:
        name: download video
        runs-on: ubuntu-latest
        steps:
        # - name: install yt-dlp deps
        #   run: |
        #       sudo apt update && sudo apt install wget python3 ffmpeg -y
        # - name: install yt-dlp
        #   run: |
        #       wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O yt-dlp
        # - name: download the video https://youtu.be/OKc-yQEiWjc
        #   run: |
        #       python3 yt-dlp https://youtu.be/OKc-yQEiWjc
        #       ls
        - name: test
          run: |
              touch video.mp4
              ls
              pwd
        - name: upload the result video to artefacts
          uses: actions/upload-artifact@v4.3.4
          with:
              path: *.*
